<?php

namespace Marstm\Test\ArrayList;

use PHPUnit\Framework\TestCase;


class ArraryListTest extends TestCase
{

    public function setUp(): void
    {

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAvg()
    {
        $average = arrayList([['foo' => 10], ['foo' => 10], ['foo' => 20], ['foo' => 40]])->avg('foo');
        var_dump($average);
//int(20)
        $average = arrayList([1, 1, 2, 4])->avg();
        var_dump($average);
        $this->assertTrue(true);
    }

    public function testWhere()
    {
        $average = arrayList([
            ['product' => 'Desk', 'price' => 200],
            ['product' => 'Chair', 'price' => 100],
            ['product' => 'Bookcase', 'price' => 150],
            ['product' => 'Door', 'price' => 100],
        ])->where("product", "Bookcase");
        var_dump($average->toArray());
        $this->assertTrue(true);
    }
}
